# generated by datamodel-codegen:
#   filename:  response_example.json
#   timestamp: 2021-11-27T19:09:05+00:00

from __future__ import annotations

from typing import List

from pydantic import BaseModel


class User(BaseModel):
    user_id: str


class Application(BaseModel):
    application_id: str


class Session(BaseModel):
    message_id: int
    session_id: str
    skill_id: str
    user: User
    application: Application
    new: bool
    user_id: str


class Button(BaseModel):
    title: str
    hide: bool


class Response(BaseModel):
    end_session: bool
    text: str
    buttons: List[Button] = []


class AliceResponse(BaseModel):
    version: str
    session: Session
    response: Response
